<?php
    /** @var \AbraaoMarques\Correios\Block\ProductPage $block */
    $product = $block->getProduct();
?>
<div class="quotation">
    <div class="fieldset">
        <label for="zipcode" class="label custom_label">Informe seu CEP</label>
        <div class="control">
            <input type="text" id="zipcode" name="zipcode" class="input-text" placeholder="12345-789" maxlength="9"/>
            <input type="hidden" name="productsku" id="productsku" value="<?= $product->getSku();?>">
            <small class="waiting">Buscando...</small>
        </div>
        <div class="display_quotation">
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "AbraaoMarques_Correios/js/input": {}
        },
        "#zipcode": {
            "AbraaoMarques_Correios/js/search": {}
        }
    }
</script>
